apiVersion: v1
kind: Service
metadata:
  name: swagger-gateway
  namespace: pogo-system
  labels:
    app: swagger-gateway
    tier: gateway
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "10000"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - port: 10000
    targetPort: 10000
    protocol: TCP
    name: http
  selector:
    app: swagger-gateway
