apiVersion: v1
kind: Service
metadata:
  name: app-bff
  namespace: pogo-system
  labels:
    app: app-bff
    tier: gateway
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "6002"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - port: 6002
    targetPort: 6002
    protocol: TCP
    name: http
  selector:
    app: app-bff

