apiVersion: v1
kind: Service
metadata:
  name: bot-bff
  namespace: pogo-system
  labels:
    app: bot-bff
    tier: gateway
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "6001"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - port: 6001
    targetPort: 6001
    protocol: TCP
    name: http
  selector:
    app: bot-bff

