apiVersion: v1
kind: Service
metadata:
  name: location-service
  namespace: pogo-system
  labels:
    app: location-service
    tier: microservice
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5003"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - port: 5003
    targetPort: 5003
    protocol: TCP
    name: http
  selector:
    app: location-service

