apiVersion: v1
kind: Service
metadata:
  name: ocr-service
  namespace: pogo-system
  labels:
    app: ocr-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 5006
      targetPort: 5006
      protocol: TCP
  selector:
    app: ocr-service
