apiVersion: v1
kind: Service
metadata:
  name: player-service
  namespace: pogo-system
  labels:
    app: player-service
    tier: microservice
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5002"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - port: 5002
    targetPort: 5002
    protocol: TCP
    name: http
  selector:
    app: player-service

