apiVersion: v1
kind: Service
metadata:
  name: raid-service
  namespace: pogo-system
  labels:
    app: raid-service
    tier: microservice
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5005"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - port: 5005
    targetPort: 5005
    protocol: TCP
    name: http
  selector:
    app: raid-service

