apiVersion: v1
kind: Service
metadata:
  name: pogo-bot
  namespace: pogo-system
  labels:
    app: pogo-bot
    tier: frontend
spec:
  type: ClusterIP
  ports:
  - port: 2000
    targetPort: 2000
    protocol: TCP
    name: http
  selector:
    app: pogo-bot

