apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pogo-ingress
  namespace: pogo-system
  labels:
    app: pogo-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/enable-cors: 'true'
    nginx.ingress.kubernetes.io/cors-allow-origin: '*'
    nginx.ingress.kubernetes.io/cors-allow-methods: 'GET, POST, PUT, DELETE, OPTIONS'
    nginx.ingress.kubernetes.io/cors-allow-headers: 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization'
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          # Swagger Gateway
          - path: /swagger(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: swagger-gateway
                port:
                  number: 10000

          # Mobile App - Root path
          - path: /()(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: pogo-app
                port:
                  number: 3000

          # Bot BFF API
          - path: /bot-api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: bot-bff
                port:
                  number: 6001

          # App BFF API
          - path: /app-api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: app-bff
                port:
                  number: 6002

          # Grafana
          - path: /grafana(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: grafana
                port:
                  number: 3000

          # Prometheus
          - path: /prometheus(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: prometheus
                port:
                  number: 9090
